apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: p596119xk-go 
  janus-idp.io/tekton: p596119xk-go
  backstage.io/kubernetes-id: p596119xk-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p596119xk-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml